### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by maxleiko** [kevoree/kevoree-js#42]
Provide a TypeScript support for `kevoree-js`

https://gist.github.com/barais/a374a75ee54b6b1f9699

**Comment by brice-morin** [comment]
:+1

I have to say JS code in general, and the Kevoree JS code in particular (with `.bind` I have to had randomly until it works) is messy (well... coming from the Java world). I hope having a proper TS API will help.

**Comment by maxleiko** [comment]
Really not that thrilled by this feature.  
The next major iteration should bring a better API for the `kevoree-js` components, meaning that you won't be forced to call `this._super` on each `start`, `stop`, `update` methods.  
I wil, also, try to see if it is possible to easily make `kevoree-js` compliant with the TypeScript generated Javascript.

**Comment by maxleiko** [comment]
Instead of writing:

```js
start: function (done) {
  this._super(function () {
    // your start code
    done();
  }.bind(this));
}
```

you will be able to write this with entities using `kevoree-entities@^8.0.0`:

```js
start: function (done) {
  // your start code
  done();
}
```

But this is just a **design trick**, because every lifecycle methods in `kevoree-js` might be asynchronous, this is why each method has a `done: Function` callback to be invoked once finished.  
So if you end up sub-classing your own component, you will inevitably be forced to use the same old syntax:

```js
// in your component that sub-classes another one
start: function (done) {
  // you need to call the this._super so that your parent-class "start" method is executed too
  this._super(function () {
    // your start code
    done();
  }.bind(this));
}
```

In the end, if this is only a `.bind(this)` problem, you could also use that syntax:

```js
start: function (done) {
  var that = this;
  this._super(function () {
    // your start code
    // use that.XXX to access your component properties
    done();
  });
}
```

It only shows a lack of JavaScript knowledge. This is not a `kevoree-js` problem :)  
Because if you don't need any access to your own component properties, you are absolutely not forced to use `.bind(this)` or `var that = this`.  

Good read: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by brice-morin** [comment]
I was not talking about that particular bind (that code is generated by Yeoman anyway), just in the cases where I am calling functions accessing my own component properties, or that kind of things. Yes, I confess my lack of JS knowledge. But as Kevoree first targeted Java, we could imagine a lot of Java developers (like me) would now give Kevoree/JS a try.... Currently, it is is not that seamless ;-)

**Comment by maxleiko** [comment]
Yes I understand the difficulties for Java

**Comment by maxleiko** [comment]
I will try to get rid of `pseudoclass` in order to produce plain old ES3/ES5 JavaScript objects so that generated TypeScript will be compliant to it.  
But it won't prevent you from learning TypeScript, which is a subset of JavaScript, which handles `super` calls the same way.  
So, in TypeScript you will also get something like this:  

```ts
class Parent {
	
	start(done: () => void) {
		console.log('parent start');
		done();
	}
}

class MyComp extends Parent {

	private foo: string;

	constructor(foo: string) {
		super();
		this.foo = foo;
	}

	start(done: () => void) {
		super.start(function () {
			console.log('doing some test', this.foo);
			done();
		}.bind(this));
		
	}
}

var c = new MyComp('bar');
c.start(function () {
	console.log('Done!');
});
```

**Comment by maxleiko** [comment]
There is an example here https://github.com/kevoree/kevoree-js.d.ts
